version: "3"
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 127.0.0.1:5440:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  jamcore:
    build: .
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    ports:
      - 127.0.0.1:3005:3005
    depends_on:
      - postgres
volumes:
  postgres_data:
